# -*- python -*-
Import('env')

ast_lib = env.SConscript('ast/SConscript')

parser_lib = env.SConscript('parser/SConscript')


p = env.Program('tkom-calculator',
                ['main.cpp']
                ,LIBS=[parser_lib, ast_lib])

Return('p')
